site_name: sdata Ontology
site_description: Semantic Data Ontology for Product Passports, Circular Economy and Digital Twins
repo_url: https://github.com/lepy/sdata-ontology
theme:
  name: material
nav:
  - Home: index.md
  - Examples: examples.md
  - Ontologies:
      - sdata-core: ontologies/sdata-core/index.md
      - sdata-material-state: ontologies/sdata-material-state.md
      - sdata-agents: ontologies/sdata-agents/index.md
      - sdata-processtypes: ontologies/sdata-processtypes/index.md
      - sdata-lifecycle: ontologies/sdata-lifecycle/index.md
      - sdata-quantities: ontologies/sdata-quantities/index.md
      - sdata-vd-interval: ontologies/sdata-vd-interval/index.md
      - sdata-vd-enum: ontologies/sdata-vd-enum/index.md
      - sdata-vd-statistical: ontologies/sdata-vd-statistical/index.md
      - sdata-vd-fuzzy: ontologies/sdata-vd-fuzzy/index.md
      - sdata-r-strategies: ontologies/sdata-r-strategies/index.md
      - sdata-core-shapes: ontologies/sdata-core-shapes/index.md
